In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
import nltk
nltk.download("popular")

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\yaswa\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\yaswa\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\yaswa\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\yaswa\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\yaswa\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]   

True

In [ ]:
df=pd.read_excel('Group3-news-text-sanitized (1).xlsx')

In [ ]:
df.head()

In [9]:
df = df.drop_duplicates('Tweet',keep='first')
df['Tweet'].count()

10138

In [10]:
df["Cleaned_Tweet"] = [re.sub(r"(@[A-Za-z0–9_]+)|[^\w\s]|#|http\S+", "", v.lower()) for v in df["Tweet"]]
df

Category  Confidence  \
0      Not Relevant      1.0000   
1      Not Relevant      1.0000   
2      Not Relevant      1.0000   
3      Not Relevant      1.0000   
4      Not Relevant      1.0000   
...             ...         ...   
10318      Relevant      0.3994   
10319      Relevant      0.3994   
10320      Relevant      0.3982   
10321  Not Relevant      0.3367   
10322      Relevant      0.3342   

                                                   Tweet  \
0                                      Hey! How are you?   
1                                         What's up man?   
2                                          I love fruits   
3                                       Summer is lovely   
4                                      My car is so fast   
...                                                  ...   
10318                        Make man pikin crash ??????   
10319  Disregard my snap story there is an angry whit...   
10320  #tornado #singapore Mac and #cheese #around th...   
10321  Check out more data on Upper Wabash reservoirs...   
10322  Drowning' - Acrylic 08.05.15 https://t.co/X17f...   

                                           Cleaned_Tweet  
0                                        hey how are you  
1                                           whats up man  
2                                          i love fruits  
3                                       summer is lovely  
4                                      my car is so fast  
...                                                  ...  
10318                              make man pikin crash   
10319  disregard my snap story there is an angry whit...  
10320  tornado singapore mac and cheese around the wo...  
10321  check out more data on upper wabash reservoirs...  
10322                          drowning  acrylic 080515   

[10138 rows x 4 columns]

In [11]:
df.drop('Tweet',axis=1)

Category  Confidence  \
0      Not Relevant      1.0000   
1      Not Relevant      1.0000   
2      Not Relevant      1.0000   
3      Not Relevant      1.0000   
4      Not Relevant      1.0000   
...             ...         ...   
10318      Relevant      0.3994   
10319      Relevant      0.3994   
10320      Relevant      0.3982   
10321  Not Relevant      0.3367   
10322      Relevant      0.3342   

                                           Cleaned_Tweet  
0                                        hey how are you  
1                                           whats up man  
2                                          i love fruits  
3                                       summer is lovely  
4                                      my car is so fast  
...                                                  ...  
10318                              make man pikin crash   
10319  disregard my snap story there is an angry whit...  
10320  tornado singapore mac and cheese around the wo...  
10321  check out more data on upper wabash reservoirs...  
10322                          drowning  acrylic 080515   

[10138 rows x 3 columns]

In [12]:
df['cat']=df['Category'].replace('Not Relevant': 0 ,'Relevant':1)

SyntaxError: invalid syntax (86809788.py, line 1)

In [13]:
vals_to_replace = {'Relevant':1, 'Not Relevant':0}
df['Category'] = df['Category'].map(vals_to_replace)

In [14]:
df['Category'].unique()

array([ 0.,  1., nan])

In [15]:
df.dropna(inplace=True)

In [16]:
df['Category'].unique()

array([0., 1.])

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [18]:
train_texts, test_texts, train_labels, test_labels = train_test_split(df['Cleaned_Tweet'],df['Category'], test_size=0.25, random_state=42)

In [19]:
vectorizer = TfidfVectorizer()

In [20]:
train_features = vectorizer.fit_transform(train_texts)
test_features = vectorizer.transform(test_texts)

In [21]:
classifier = LogisticRegression()
classifier.fit(train_features, train_labels)

LogisticRegression()

In [22]:
predictions = classifier.predict(test_features)

In [23]:
accuracy = accuracy_score(test_labels, predictions)
print("Accuracy:", accuracy)

Accuracy: 0.8107467404188068


In [24]:
from sklearn.naive_bayes import MultinomialNB
classifier1 = MultinomialNB()
classifier1.fit(train_features, train_labels)

MultinomialNB()

In [25]:
predictions = classifier1.predict(test_features)

In [28]:
predictions

array([1., 1., 0., ..., 1., 0., 0.])

In [26]:
accuracy = accuracy_score(test_labels, predictions)
print("Accuracy:", accuracy)

Accuracy: 0.8060055314105097


In [27]:
text='hello world'

In [ ]:
vectorizer = TfidfVectorizer()